# -*- coding: utf-8 -*-
"""TP--Paleta_colores_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14t0p-_0THnqRc-YPuH6InhDSWjESJDPj

# Paleta de colores

### Idea

Aplicar procesamiento de imágenes con Python para extraer colores predominantes de una imagen o foto, para identificar los tonos dominantes y ejecutarlos como paleta de colores.
"""

import os
from google.colab import files
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display, HTML

uploaded = files.upload()

# obtener el nombre del archivo subido
image_path = list(uploaded.keys())[0]
print("Imagen cargada:", image_path)

def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % rgb

def get_dominant_colors(image_path, n_colors):
    img = Image.open(image_path)

    img = img.resize((150, 150))
    img = img.convert("P", palette=Image.ADAPTIVE, colors=n_colors)
    img = img.convert("RGB")

    colors = img.getcolors(150*150)
    colors.sort(reverse=True)

    dominant_colors = [color[1] for color in colors[:n_colors]]
    return dominant_colors

def save_palette_image(colors, output_path):
    width = 500
    height = 100 * len(colors)

    palette_img = Image.new("RGB", (width, height), (255, 255, 255))
    draw = ImageDraw.Draw(palette_img)

    font = ImageFont.load_default()

    for i, color in enumerate(colors):
        y0 = i * 100
        y1 = y0 + 100

        draw.rectangle([0, y0, 200, y1], fill=color)

        hex_code = rgb_to_hex(color)
        draw.text((220, y0 + 35), hex_code, fill=(0, 0, 0), font=font)

    palette_img.save(output_path, "JPEG")

n_colors = int(input("¿Cuantos colores detectar? "))

colors = get_dominant_colors(image_path, n_colors)

print("\n/* Muestras de colores en formato hexadecimal */")
for i, color in enumerate(colors, start=1):
    hex_code = rgb_to_hex(color)
    print(f"{i}.Imagen0001-{i}-hex {{ color: {hex_code}; }}")

guardar = input("¿Desea descargar la paleta como JPEG? (s/n): ").strip().lower()

if guardar == "s":
    # obtener nombre base de la imagen (sin extensión)
    base_name = os.path.splitext(os.path.basename(image_path))[0]

    output_path = f"{base_name}_paleta.jpg"

    save_palette_image(colors, output_path)
    files.download(output_path)

    print(f"Archivo generado: {output_path}")
else:
    print("Operación cancelada. No se generó ningún archivo.")

def mostrar_paleta(colors):
    bloques = ""

    for i, color in enumerate(colors, start=1):
        hex_code = '#%02x%02x%02x' % color

        bloques += f"""
        <div style="
            display:flex;
            align-items:center;
            margin:10px 0;
            font-family:monospace;
        ">
            <div style="
                width:100px;
                height:50px;
                background:{hex_code};
                border:1px solid #000;
                margin-right:10px;
            "></div>
            <span>{i}. {hex_code}</span>
        </div>
        """

    display(HTML(bloques))

mostrar_paleta(colors)

"""IDEAS FUTURAs:
* añadir qué porcentaje de color

* detallar qué emoción transmite cierto color

¿qué transmite eso? ¿qué implica?

 Ejemplos claros
 Imagen con mucho azul

* Datos: 60% azul
* Interpretación: transmite calma  
sensación de frío o tranquilidad
puede ser cielo, agua, etc.
* Imagen con rojo dominante: Datos: 50% rojo
Interpretación: energía  
intensidad / pasión

* Mucho verde
 Interpretación: naturaleza, frescura, salud

 Ejemplo:

Se identificó que el color predominante es el azul (58%).
Esto sugiere que la imagen transmite sensaciones de calma y tranquilidad, asociadas comúnmente a este color según la psicología del color.

IDEAS FUTURAS:

uso en marketing
impacto visual
tipo de contenido (natural, urbano, etc.)
En una frase
 Interpretar = explicar qué significan los colores, no solo medirlos

Clasificar imágenes según:

cálidas / frías
oscuras / brillantes
saturadas / suaves
"""